name: 'Setup Solr'
description: 'Setup Solr'
author: 'OSGeo'
branding:
  icon: 'database'
  color: 'orange'
inputs:
  solr_version:
    description: 'Version of Solr to use'
    required: false
    default: 'latest'
  host_port:
    description: 'The port of host'
    required: false
    default: 8983
  container_port:
    description: 'The port of container'
    required: false
    default: 8983

runs:
  using: 'docker' 
  image: 'Dockerfile'
