name: solr_ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install curl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
    - uses: OSGeo/solr-action@main
      with:
        solr_version: latest
        host_port: 8983
        container_port: 8983
    - name: check whether Solr is running
      run: curl http://localhost:8983/solr
